# Configuration

In [37]:
library(readr)
library(GRaNIE)
library(Seurat)
library(Signac)
library(cowplot)
library(data.table)
library(ggplot2)
library(patchwork)
library(stringr)
library(Matrix)
library(org.Hs.eg.db) # 人类数据
library(AnnotationDbi)
library(dplyr)
library(tibble)

# Data read

In [38]:


cell_type <- "HepG2"

data_path <- paste0("/home/liyang/BioWuYan/dygmamba_project/data/cell_line/", cell_type, "/process/")


# The only need input are the atac_dir and rna_dir

atac_dir <- paste0(data_path,  "R/atac/")

rna_dir <- paste0(data_path,  "R/rna/")

############################################################################################
#******************************** Data Read --- ATAC ***************************************
############################################################################################

mtx <- readMM(paste0(atac_dir, "sparse.mtx"))

cellinfo <- fread(paste0(atac_dir, "cellinfo.csv"), header = T, data.table = F)

atacinfo <- fread(paste0(atac_dir, "atacinfo.csv"), header = T, data.table = F)

rownames(mtx) <- cellinfo$V1
colnames(mtx) <- atacinfo$V1

meta <- cellinfo
rownames(meta) <- cellinfo$V1

if(identical(rownames(meta), rownames(mtx))){
        # 行需为 feature
    print("Info identical, Can create Seurat Object")
    mtx_transposed <- t(mtx) 

    atac_seurat <- CreateSeuratObject(count = mtx_transposed, meta.data = meta, assay = "ATAC")
}

rownames(atac_seurat) <- sub("-", ":", rownames(atac_seurat)) # 确保只有第一个是冒号

############################################################################################
#******************************** Data Read --- RNA ***************************************
############################################################################################


rna_mtx <- readMM(paste0(rna_dir, "sparse.mtx"))

rna_cellinfo <- fread(paste0(rna_dir, "cellinfo.csv"), header = T, data.table = F)

rna_info <- fread(paste0(rna_dir, "rnainfo.csv"), header = T, data.table = F)

rownames(rna_mtx) <- rna_cellinfo$V1
colnames(rna_mtx) <- rna_info$Geneid

meta <- rna_cellinfo
rownames(meta) <- rna_cellinfo$V1


    
print("Create Seurat Object")
rna_mtx_transposed <- t(rna_mtx)

rna_seurat <- CreateSeuratObject(count = rna_mtx_transposed, meta.data = meta, assay = "RNA")

[1] "Info identical, Can create Seurat Object"

Warning message:
"Data is of class dgTMatrix. Coercing to dgCMatrix."

[1] "Create Seurat Object"

Warning message:
"Data is of class dgTMatrix. Coercing to dgCMatrix."

# Data process

In [39]:

n_bins <- 50 

rna_seurat <- NormalizeData(rna_seurat)
rna_seurat <- FindVariableFeatures(rna_seurat)
rna_seurat <- ScaleData(rna_seurat)
rna_seurat <- RunPCA(rna_seurat, verbose = FALSE) # 生成 PCA 降维

rna_seurat <- RunUMAP(rna_seurat, dims = 1:30)
rna_kmeans <- kmeans(Embeddings(rna_seurat, "umap"), centers = n_bins)

rna_seurat$metacell_id <- paste0("bin_", rna_kmeans$cluster)


atac_seurat <- RunTFIDF(atac_seurat)
atac_seurat <- FindTopFeatures(atac_seurat, min.cutoff = 'q0')
atac_seurat <- RunSVD(atac_seurat) # ATAC 的降维通常叫 LSI 或 SVD

# 3. 运行 UMAP (基于 lsi)
atac_seurat <- RunUMAP(atac_seurat, reduction = 'lsi', dims = 2:30)

atac_kmeans <- kmeans(Embeddings(atac_seurat, "umap"), centers = n_bins)
atac_seurat$metacell_id <- paste0("bin_", atac_kmeans$cluster)

Normalizing layer: counts

Finding variable features for layer counts

Centering and scaling data matrix

14:02:31 UMAP embedding parameters a = 0.9922 b = 1.112

14:02:31 Read 500 rows and found 30 numeric columns

14:02:31 Using Annoy for neighbor search, n_neighbors = 30

14:02:31 Building Annoy index with metric = cosine, n_trees = 50

0%   10   20   30   40   50   60   70   80   90   100%

[----|----|----|----|----|----|----|----|----|----|

*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
|

14:02:31 Writing NN index file to temp file /tmp/RtmpihyBYP/file18da01c0801c8

14:02:31 Searching Annoy index using 1 thread, search_k = 3000

14:02:31 Annoy recall = 100%

14:02:33 Commencing smooth kNN distance calibration using 1 thread
 with target n_neighbors = 30

14:02:35 Initializing from normalized Laplacian + noise (using RSpectra)

14:02:35 Commencing optimization for 500 epochs, with 15574 positive edges

14:02:35 Using rng type: pcg

14:02:37 Optimization finished

Performing TF-IDF normalization

Running SVD

Scaling cell embeddings

14:02:51 UMAP embedding parameters a = 0.9922 b = 1.112

14:02:51 Read 500 rows and found 29 numeric columns

14:02:51 Using Annoy for neighbor search, n_neighbors = 30

14:02:51 Building Annoy index with metric = cosine, n_trees = 50

0%   10   20   30   40   50   60   70   80   90   100%

[----|----|----|----|----|----|----|----|----|----|

*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
|

14:02:51 Writing NN index file to temp file /tmp/RtmpihyBYP/file18da01022d78d

14:02:51 Searching Annoy index using 1 thread, search_k = 3000

14:02:51 Annoy recall = 100%

14:02:53 Commencing smooth kNN distance calibration using 1 thread
 with target n_neighbors = 30

14:02:55 Initializing from normalized Laplacian + noise (using RSpectra)

14:02:55 Commencing optimization for 500 epochs, with 15708 positive edges

14:02:55 Using rng type: pcg

14:02:57 Optimization finished

In [40]:
# --- 处理 RNA ---
DefaultAssay(rna_seurat) <- "RNA" # 显式设置
# 聚合
rna_assay_name <- DefaultAssay(rna_seurat)
pb_list_rna <- AggregateExpression(rna_seurat, group.by = "metacell_id", 
                                   assays = rna_assay_name, slot = "counts")
pb_rna <- pb_list_rna[[rna_assay_name]] # 动态提取

# --- 处理 ATAC ---
atac_assay_name <- DefaultAssay(atac_seurat)
pb_list_atac <- AggregateExpression(atac_seurat, group.by = "metacell_id", 
                                    assays = atac_assay_name, slot = "counts")
pb_atac <- pb_list_atac[[atac_assay_name]]


# --- 对齐数据 ---
common_bins <- intersect(colnames(pb_rna), colnames(pb_atac))
pb_rna <- pb_rna[, common_bins]
pb_atac <- pb_atac[, common_bins]

# GRN inference

In [41]:

# 1. 修正 ATAC 矩阵：将行名提取为 "peakID" 列
pb_atac_df <- as.data.frame(pb_atac) %>% 
  rownames_to_column(var = "peakID")

# 2. 修正 RNA 矩阵：将行名提取为 "geneID" 列
pb_rna_df <- as.data.frame(pb_rna) %>% 
  rownames_to_column(var = "geneID")

# 检查一下现在长什么样 (你应该能看到第一列变成了 ID)
print(head(pb_atac_df[, 1:5])) 

metadata_df <- data.frame(sample_id = common_bins, cell_type = "SingleType")

GRN <- initializeGRN(objectMetadata = list(name = "Metacell_GRN"), 
                      genomeAssembly = "hg38", 
                      outputFolder = "GRaNIE_Results")

                    peakID bin-1 bin-10 bin-11 bin-12
1 chr1:100037630-100038936     7      0      2      6
2 chr1:100132442-100133739     7      0      0      2
3     chr1:1001683-1001983     2      4      1      4
4 chr1:100249267-100250230     0      2      4      3
5 chr1:100265726-100266824     2      6      0      2
6 chr1:100320471-100321812     0      0      2      2

INFO [2026-02-02 14:02:57] Empty GRN object created successfully. Type the object name (e.g., GRN) to retrieve summary information about it at any time.

INFO [2026-02-02 14:02:57]  Default output folder: /home/liyang/BioWuYan/dygmamba_project/model/GRaNIE/code/GRaNIE_Results/

INFO [2026-02-02 14:02:57]  Genome assembly: hg38

INFO [2026-02-02 14:02:57] Finished successfully. Execution time: 0 secs

In [42]:

current_symbols <- pb_rna_df$geneID # 假设你之前的 ID 列叫 geneID
ensembl_ids <- mapIds(org.Hs.eg.db,
                      keys = current_symbols,
                      column = "ENSEMBL",
                      keytype = "SYMBOL",
                      multiVals = "first")


pb_rna_df_fixed <- pb_rna_df %>%
            mutate(ensemblID = ensembl_ids[geneID]) %>% # 根据旧 ID 匹配新 ID
            dplyr::filter(!is.na(ensemblID)) %>%               # 去掉没找到 Ensembl ID 的基因
            dplyr::distinct(ensemblID, .keep_all = TRUE)       # 去掉重复的 ID (非常重要！)

pb_rna_clean <- pb_rna_df_fixed %>%
            dplyr::select(ensemblID, where(is.numeric)) 


GRN <- addData(GRN, 
               counts_peaks = pb_atac_df,      # ATAC 数据不变
               counts_rna = pb_rna_clean,   # 使用修复后的 RNA 数据
               sampleMetadata = metadata_df,   # 元数据不变
               idColumn_peaks = "peakID",      # ATAC 的 ID 列名
               idColumn_RNA = "ensemblID",     # ⚠️ 注意：这里改成新的列名
               force = TRUE)

'select()' returned 1:many mapping between keys and columns

INFO [2026-02-02 14:02:58]  Normalizing data using the package DESeq2 with a standard size factor normalization.

INFO [2026-02-02 14:02:58]  Normalizing data using the package limma with the following method: limma_quantile

INFO [2026-02-02 14:02:59] Parsing provided metadata...

INFO [2026-02-02 14:02:59] Subset RNA and peaks and keep only shared samples

INFO [2026-02-02 14:02:59]  Number of samples for RNA before filtering: 50

INFO [2026-02-02 14:02:59]  Number of samples for peaks before filtering: 50

INFO [2026-02-02 14:02:59]  50 samples (bin-1,bin-10,bin-11,bin-12,bin-13,bin-14,bin-15,bin-16,bin-17,bin-18,bin-19,bin-2,bin-20,bin-21,bin-22,bin-23,bin-24,bin-25,bin-26,bin-27,bin-28,bin-29,bin-3,bin-30,bin-31,bin-32,bin-33,bin-34,bin-35,bin-36,bin-37,bin-38,bin-39,bin-4,bin-40,bin-41,bin-42,bin-43,bin-44,bin-45,bin-46,bin-47,bin-48,bin-49,bin-5,bin-50,bin-6,bin-7,bin-8,bin-9) are shared between the peaks and RNA-Seq data

INFO [2026-02-02 14:02:59]  Number of samples for RNA after filtering: 50

INFO [2026-02-02 14:02:59]  Number of samples for peaks data after filtering: 50

INFO [2026-02-02 14:02:59]  Finished successfully. Execution time: 0 secs

INFO [2026-02-02 14:02:59] Storing GRN@data$peaks$counts matrix as sparse matrix because fraction of 0s is > 0.1 (0.64)

INFO [2026-02-02 14:02:59] Final dimensions of data:

INFO [2026-02-02 14:02:59]  RNA  : 1995 x 50 (rows x columns)

INFO [2026-02-02 14:02:59]  peaks: 31555 x 50 (rows x columns)

INFO [2026-02-02 14:02:59] Generate 1 permutations of RNA-counts

INFO [2026-02-02 14:02:59] Check for overlapping peaks...

INFO [2026-02-02 14:02:59] Adding peak and gene annotation...

INFO [2026-02-02 14:02:59]  Calculate statistics for each peak (mean and CV)

WARN [2026-02-02 14:02:59] For the chosen genome assembly version and package function, particular genome annotation packages are required but not installed. Please install and re-run this function.

Execute the following line in R to install the missing package(s): `BiocManager::install(c("TxDb.Hsapiens.UCSC.hg38.knownGene"))`.
This warning may or may not be ignored. Carefully check its significance and whether it may affect the results.


Warning message in .checkAndLogWarningsAndErrors(NULL, message, isWarning = TRUE):
"For the chosen genome assembly version and package function, particular genome annotation packages are required but not installed. Please install and re-run this function.

Execute the following line in R to install the missing package(s): `BiocManager::install(c("TxDb.Hsapiens.UCSC.hg38.knownGene"))`.
This warning may or may not be ignored. Carefully check its significance and whether it may affect the results.
"
WARN [2026-02-02 14:02:59] addData: The package ChIPseeker is currently not installed, which is needed for additional peak annotation that can be useful for further downstream analyses.  You may want to install it and re-run this function. However, this is optional and except for some missing additional annotation columns, there is no limitation.

Execute the following line in R to install the missing package(s): `BiocManager::install(c("ChIPseeker"))`.
This warning may or may not be ignored. Carefully check its significance and whether it may affect the results.


Warning message in .checkAndLogWarningsAndErrors(NULL, message, isWarning = isWarning):
"addData: The package ChIPseeker is currently not installed, which is needed for additional peak annotation that can be useful for further downstream analyses.  You may want to install it and re-run this function. However, this is optional and except for some missing additional annotation columns, there is no limitation.

Execute the following line in R to install the missing package(s): `BiocManager::install(c("ChIPseeker"))`.
This warning may or may not be ignored. Carefully check its significance and whether it may affect the results.
"
INFO [2026-02-02 14:02:59]  Calculate statistics for each of the 1995 genes that were provided with the RNA-seq data (mean and CV)

INFO [2026-02-02 14:02:59] Retrieving genome annotation data from AnnotationHub for hg38... This may take a while

loading from cache

INFO [2026-02-02 14:03:11] Finished successfully. Execution time: 13.5 secs

In [43]:
# 1. 从本地数据库提取 Symbol 到 Ensembl 的对照表
keys <- keys(org.Hs.eg.db, keytype = "SYMBOL")
mapping <- select(org.Hs.eg.db, 
                  keys = keys, 
                  columns = c("ENSEMBL", "SYMBOL"), 
                  keytype = "SYMBOL")

# 2. 整理成 GRaNIE 格式 (使用了 dplyr:: 前缀来防止报错)
translation_table_local <- mapping %>%
                  dplyr::rename(TF_name = SYMBOL, TF_ensembl = ENSEMBL) %>%
                  dplyr::filter(!is.na(TF_ensembl)) %>%        # <--- 修正点：加上 dplyr::
                  dplyr::distinct(TF_name, .keep_all = TRUE)   # <--- 修正点：加上 dplyr::

print(paste("本地构建了", nrow(translation_table_local), "个基因的对照表"))

# 使用本地表运行 addTFBS
GRN <- addTFBS(GRN, 
               source = "JASPAR2024", 
               translationTable = translation_table_local)



# 2. 计算 TFBS 与 Peak 的重叠
# 这一步现在会使用 JASPAR 的 Motif 进行扫描
GRN <- overlapPeaksAndTFBS(GRN)


# 3. 计算 TF-Peak 链接
GRN <- addConnections_TF_peak(GRN, 
                              corMethod = "pearson")

# 4. 计算 Peak-Gene 链接
GRN <- addConnections_peak_gene(GRN,  
                                corMethod = "pearson")

'select()' returned 1:many mapping between keys and columns

[1] "本地构建了 37765 个基因的对照表"

INFO [2026-02-02 14:03:13] Querying JASPAR2024 database. This may take a while.

Retrieving a list of species available in JASPAR release 2022.

INFO [2026-02-02 14:03:26] Retrieving gene annotation for JASPAR TFs. This may take a while.

INFO [2026-02-02 14:03:30]  Retrieving BioMart database succeeded

INFO [2026-02-02 14:03:31]  Retrieving genome annotation succeeded

INFO [2026-02-02 14:03:31]  TF statistics:

INFO [2026-02-02 14:03:31]   Number of TFs as returned by JASPAR: 720

INFO [2026-02-02 14:03:31]   Number of TFs with a unique mapping to an Ensembl ID: 619

INFO [2026-02-02 14:03:31]   Number of TFs with a non-unique mapping to an Ensembl ID: 33 (MA0153.2, MA0468.1, MA0482.3, MA0486.2, MA0509.3, MA0630.2, MA0653.1, MA0657.2, MA0715.1, MA0736.1, MA0743.3, MA0749.2, MA0772.2, MA0773.1, MA0821.2, MA0831.3, MA0842.3, MA0849.1, MA0855.1, MA0864.3, MA0879.3, MA1113.3, MA1115.2, MA1421.1, MA1525.3, MA1555.1, MA1583.2, MA1649.2, MA1715.1, MA1720.2, MA1723.2, MA2333.1, MA2335.1)

INFO [2026-02-02 14:03:31]   Removing ambiguously mapping TFs

INFO [2026-02-02 14:03:31] Found 619 matching TFs: MA0003.5, MA0009.2, MA0014.4, MA0017.3, MA0018.5, MA0024.3, MA0025.3, MA0027.3, MA0028.3, MA0030.2, MA0031.2, MA0032.2, MA0033.2, MA0035.5, MA0036.4, MA0038.3, MA0039.5, MA0041.3, MA0042.2, MA0043.4, MA0046.3, MA0047.4, MA0048.3, MA0051.2, MA0052.5, MA0056.3, MA0058.4, MA0060.4, MA0062.4, MA0063.3, MA0066.2, MA0067.3, MA0068.2, MA0069.1, MA0070.2, MA0071.1, MA0072.2, MA0073.2, MA0075.4, MA0076.3, MA0077.2, MA0079.5, MA0081.3, MA0083.3, MA0084.2, MA0088.2, MA0090.4, MA0093.4, MA0098.4, MA0100.4, MA0101.1, MA0102.5, MA0103.4, MA0104.5, MA0105.4, MA0106.3, MA0107.1, MA0112.4, MA0113.4, MA0114.5, MA0130.1, MA0131.3, MA0132.3, MA0137.4, MA0138.3, MA0139.2, MA0141.4, MA0143.5, MA0144.3, MA0147.4, MA0148.5, MA0154.5, MA0155.1, MA0156.4, MA0158.2, MA0160.3, MA0161.3, MA0162.5, MA0163.1, MA0258.2, MA0442.3, MA0463.3, MA0464.3, MA0465.3, MA0466.4, MA0469.4, MA0470.3, MA0471.3, MA0472.2, MA0473.4, MA0475.3, MA0476.2, MA0477.3, MA0478.2, MA0479.2, MA0481.4, MA0484.3, MA0485.3, MA0488.2, MA0490.3, MA0491.3, MA0492.2, MA0493.3, MA0495.4, MA0496.4, MA0497.2, MA0498.3, MA0499.3, MA0500.3, MA0502.3, MA0504.2, MA0507.3, MA0508.4, MA0510.3, MA0511.2, MA0516.3, MA0522.4, MA0523.2, MA0524.3, MA0525.2, MA0526.5, MA0527.2, MA0528.3, MA0592.4, MA0593.2, MA0594.3, MA0595.1, MA0596.1, MA0597.3, MA0598.4, MA0599.1, MA0600.3, MA0605.3, MA0607.2, MA0609.3, MA0610.2, MA0612.3, MA0613.1, MA0616.3, MA0618.2, MA0620.4, MA0623.2, MA0625.3, MA0627.3, MA0628.2, MA0632.3, MA0634.2, MA0635.2, MA0636.1, MA0638.2, MA0639.2, MA0640.3, MA0641.1, MA0642.3, MA0644.3, MA0645.2, MA0646.2, MA0647.2, MA0648.2, MA0649.2, MA0651.3, MA0652.2, MA0654.2, MA0655.1, MA0656.2, MA0658.2, MA0660.1, MA0661.2, MA0662.2, MA0663.1, MA0664.2, MA0665.1, MA0666.3, MA0667.1, MA0669.1, MA0670.2, MA0671.2, MA0672.2, MA0673.2, MA0674.2, MA0675.2, MA0678.1, MA0679.3, MA0681.3, MA0682.3, MA0683.2, MA0684.3, MA0685.2, MA0686.2, MA0687.2, MA0688.2, MA0689.1, MA0690.3, MA0691.1, MA0692.2, MA0694.2, MA0695.2, MA0696.1, MA0698.2, MA0699.2, MA0700.3, MA0701.3, MA0702.3, MA0703.3, MA0706.2, MA0707.3, MA0708.3, MA0710.2, MA0711.2, MA0712.3, MA0713.1, MA0714.2, MA0716.2, MA0717.2, MA0718.2, MA0719.2, MA0721.2, MA0722.2, MA0723.3, MA0724.1, MA0725.2, MA0726.2, MA0727.2, MA0729.1, MA0730.1, MA0731.1, MA0732.2, MA0733.2, MA0735.2, MA0737.1, MA0738.2, MA0740.2, MA0741.1, MA0742.2, MA0744.3, MA0745.3, MA0746.3, MA0747.2, MA0748.3, MA0750.3, MA0751.2, MA0752.2, MA0753.3, MA0754.3, MA0755.2, MA0756.3, MA0757.2, MA0758.1, MA0759.3, MA0760.2, MA0761.3, MA0762.2, MA0763.2, MA0764.4, MA0765.4, MA0766.3, MA0767.2, MA0769.3, MA0770.1, MA0771.1, MA0774.1, MA0775.2, MA0776.1, MA0777.1, MA0778.2, MA0779.2, MA0780.1, MA0781.2, MA0782.3, MA0783.1, MA0784.3, MA0785.2, MA0786.2, MA0787.1, MA0788.1, MA0789.1, MA0790.2, MA0791.2, MA0792.1, MA0793.2, MA0794.1, MA0795.1, MA0796.1, MA0797.1, MA0798.3, MA0799.3, MA0800.2, MA0801.1, MA0802.2, MA0803.1, MA0804.2, MA0805.1, MA0806.1, MA0807.1, MA0808.1, MA0809.3, MA0810.2, MA0811.2, MA0812.2, MA0813.1, MA0814.3, MA0815.1, MA0817.2, MA0818.2, MA0819.3, MA0820.2, MA0822.1, MA0823.1, MA0825.2, MA0826.1, MA0827.1, MA0828.3, MA0829.3, MA0830.3, MA0833.3, MA0834.2, MA0835.3, MA0836.3, MA0837.3, MA0838.1, MA0839.2, MA0841.2, MA0843.2, MA0844.2, MA0845.1, MA0846.2, MA0847.4, MA0848.1, MA0850.1, MA0852.3, MA0856.1, MA0861.2, MA0862.1, MA0863.1, MA0865.3, MA0866.1, MA0867.3, MA0868.3, MA0871.3, MA0872.1, MA0873.2, MA0875.2, MA0876.2, MA0877.4, MA0878.3, MA0882.2, MA0884.2, MA0886.2, MA0887.2, MA0888.2, MA0889.2, MA0890.2, MA0891.2, MA0892.2, MA0893.3, MA0894.2, MA0895.2, MA0899.2, MA0900.3, MA0901.3, MA0902.3, MA0903.2, MA0904.3, MA0905.2, MA0906.2, MA0907.2, MA0908.2, MA0910.3, MA0912.2, MA0913.3, MA0914.2, MA1099.3, MA1100.3, MA1101.3, MA1102.3, MA1103.3, MA1104.3, MA1105.3, MA1106.2, MA1107.3, MA1108.3, MA1109.2, MA1111.2, MA1112.3, MA1114.2, MA1116.2, MA1117.2, MA1118.2, MA1119.2, MA1120.2, MA1121.2, MA1122.2, MA1123.3, MA1124.1, MA1125.2, MA1140.3, MA1150.2, MA1151.2, MA1152.2, MA1154.2, MA1155.1, MA1418.2, MA1419.2, MA1420.1, MA1463.2, MA1464.2, MA1466.2, MA1468.1, MA1470.2, MA1471.2, MA1473.2, MA1474.2, MA1475.2, MA1478.2, MA1479.2, MA1480.2, MA1481.2, MA1483.3, MA1484.2, MA1485.1, MA1487.3, MA1489.1, MA1491.3, MA1493.1, MA1494.2, MA1495.2, MA1496.2, MA1497.2, MA1498.3, MA1499.2, MA1500.2, MA1501.2, MA1502.2, MA1503.2, MA1504.2, MA1505.2, MA1506.2, MA1507.2, MA1508.2, MA1509.1, MA1511.2, MA1512.2, MA1513.2, MA1514.2, MA1515.2, MA1516.2, MA1517.2, MA1519.2, MA1520.2, MA1521.2, MA1522.2, MA1523.2, MA1527.2, MA1528.2, MA1529.2, MA1530.2, MA1531.2, MA1532.2, MA1533.2, MA1534.2, MA1535.2, MA1536.2, MA1537.2, MA1538.1, MA1539.1, MA1541.2, MA1542.2, MA1544.2, MA1545.2, MA1546.2, MA1547.2, MA1548.2, MA1549.2, MA1550.2, MA1552.2, MA1553.2, MA1554.2, MA1556.1, MA1557.1, MA1558.2, MA1559.2, MA1560.2, MA1561.2, MA1562.2, MA1563.2, MA1564.2, MA1565.2, MA1566.3, MA1568.2, MA1569.2, MA1570.1, MA1571.1, MA1572.1, MA1574.2, MA1575.2, MA1576.2, MA1577.2, MA1578.2, MA1579.2, MA1580.1, MA1581.2, MA1584.2, MA1585.2, MA1587.1, MA1588.1, MA1589.2, MA1592.2, MA1593.2, MA1594.1, MA1596.1, MA1597.1, MA1599.2, MA1600.2, MA1601.2, MA1602.2, MA1630.3, MA1631.2, MA1632.2, MA1633.2, MA1634.2, MA1635.2, MA1636.2, MA1637.2, MA1638.2, MA1639.2, MA1640.2, MA1641.2, MA1642.2, MA1643.2, MA1644.2, MA1645.2, MA1646.2, MA1648.2, MA1650.2, MA1651.2, MA1652.2, MA1653.2, MA1654.2, MA1655.2, MA1656.2, MA1657.2, MA1683.2, MA1707.2, MA1708.2, MA1709.2, MA1710.2, MA1711.2, MA1712.2, MA1713.2, MA1714.2, MA1716.2, MA1717.2, MA1718.1, MA1719.2, MA1721.2, MA1722.2, MA1725.2, MA1726.2, MA1727.2, MA1728.2, MA1729.2, MA1730.2, MA1731.2, MA1928.2, MA1929.2, MA1930.2, MA1951.2, MA1959.2, MA1961.2, MA1963.2, MA1964.2, MA1965.2, MA1968.2, MA1969.2, MA1970.2, MA1971.2, MA1972.1, MA1973.2, MA1974.2, MA1975.2, MA1976.2, MA1977.2, MA1978.2, MA1979.2, MA1980.1, MA1981.2, MA1982.2, MA1983.2, MA1984.2, MA1985.1, MA1986.2, MA1987.2, MA2003.2, MA2093.1, MA2094.1, MA2096.1, MA2097.1, MA2098.1, MA2099.1, MA2100.1, MA2101.1, MA2102.1, MA2117.1, MA2118.1, MA2119.1, MA2120.1, MA2121.1, MA2324.1, MA2325.1, MA2326.1, MA2327.1, MA2328.1, MA2329.1, MA2330.1, MA2331.1, MA2332.1, MA2334.1, MA2336.1, MA2341.1

INFO [2026-02-02 14:03:31] Use all TF from the JASPAR2024 database

INFO [2026-02-02 14:03:31] Filtering the following 559 TFs as they are not present in the RNA-Seq data: MA0003.5, MA0009.2, MA0014.4, MA0024.3, MA0025.3, MA0027.3, MA0028.3, MA0030.2, MA0031.2, MA0032.2, MA0033.2, MA0035.5, MA0039.5, MA0041.3, MA0042.2, MA0043.4, MA0046.3, MA0047.4, MA0048.3, MA0051.2, MA0052.5, MA0058.4, MA0062.4, MA0063.3, MA0066.2, MA0067.3, MA0068.2, MA0069.1, MA0070.2, MA0071.1, MA0072.2, MA0073.2, MA0075.4, MA0081.3, MA0083.3, MA0084.2, MA0090.4, MA0098.4, MA0100.4, MA0102.5, MA0103.4, MA0104.5, MA0106.3, MA0107.1, MA0112.4, MA0113.4, MA0130.1, MA0131.3, MA0132.3, MA0137.4, MA0138.3, MA0139.2, MA0141.4, MA0143.5, MA0144.3, MA0147.4, MA0154.5, MA0155.1, MA0156.4, MA0158.2, MA0160.3, MA0161.3, MA0162.5, MA0163.1, MA0258.2, MA0442.3, MA0463.3, MA0464.3, MA0465.3, MA0466.4, MA0470.3, MA0471.3, MA0472.2, MA0473.4, MA0475.3, MA0476.2, MA0477.3, MA0478.2, MA0479.2, MA0481.4, MA0484.3, MA0485.3, MA0488.2, MA0491.3, MA0492.2, MA0493.3, MA0495.4, MA0496.4, MA0497.2, MA0498.3, MA0499.3, MA0500.3, MA0502.3, MA0504.2, MA0507.3, MA0508.4, MA0510.3, MA0511.2, MA0516.3, MA0523.2, MA0524.3, MA0525.2, MA0526.5, MA0527.2, MA0528.3, MA0592.4, MA0593.2, MA0594.3, MA0595.1, MA0596.1, MA0597.3, MA0598.4, MA0599.1, MA0600.3, MA0605.3, MA0607.2, MA0609.3, MA0610.2, MA0612.3, MA0613.1, MA0616.3, MA0618.2, MA0620.4, MA0623.2, MA0625.3, MA0627.3, MA0628.2, MA0632.3, MA0634.2, MA0635.2, MA0636.1, MA0638.2, MA0639.2, MA0640.3, MA0641.1, MA0642.3, MA0644.3, MA0646.2, MA0647.2, MA0648.2, MA0649.2, MA0651.3, MA0652.2, MA0654.2, MA0655.1, MA0656.2, MA0658.2, MA0660.1, MA0661.2, MA0662.2, MA0665.1, MA0666.3, MA0667.1, MA0669.1, MA0672.2, MA0673.2, MA0674.2, MA0675.2, MA0678.1, MA0679.3, MA0681.3, MA0682.3, MA0683.2, MA0684.3, MA0685.2, MA0686.2, MA0687.2, MA0688.2, MA0689.1, MA0690.3, MA0691.1, MA0692.2, MA0694.2, MA0695.2, MA0696.1, MA0698.2, MA0699.2, MA0700.3, MA0701.3, MA0702.3, MA0703.3, MA0706.2, MA0707.3, MA0708.3, MA0710.2, MA0711.2, MA0712.3, MA0713.1, MA0714.2, MA0716.2, MA0717.2, MA0718.2, MA0719.2, MA0721.2, MA0722.2, MA0723.3, MA0724.1, MA0725.2, MA0726.2, MA0727.2, MA0731.1, MA0732.2, MA0733.2, MA0735.2, MA0737.1, MA0738.2, MA0740.2, MA0741.1, MA0742.2, MA0744.3, MA0745.3, MA0747.2, MA0748.3, MA0751.2, MA0752.2, MA0753.3, MA0754.3, MA0755.2, MA0756.3, MA0757.2, MA0758.1, MA0759.3, MA0760.2, MA0761.3, MA0762.2, MA0764.4, MA0765.4, MA0766.3, MA0767.2, MA0769.3, MA0770.1, MA0771.1, MA0774.1, MA0775.2, MA0776.1, MA0777.1, MA0778.2, MA0779.2, MA0780.1, MA0781.2, MA0782.3, MA0783.1, MA0784.3, MA0786.2, MA0787.1, MA0788.1, MA0789.1, MA0790.2, MA0791.2, MA0792.1, MA0793.2, MA0794.1, MA0796.1, MA0798.3, MA0799.3, MA0800.2, MA0802.2, MA0803.1, MA0804.2, MA0805.1, MA0806.1, MA0807.1, MA0808.1, MA0809.3, MA0810.2, MA0811.2, MA0812.2, MA0813.1, MA0814.3, MA0815.1, MA0817.2, MA0818.2, MA0819.3, MA0820.2, MA0822.1, MA0823.1, MA0825.2, MA0826.1, MA0827.1, MA0828.3, MA0829.3, MA0830.3, MA0833.3, MA0835.3, MA0836.3, MA0837.3, MA0838.1, MA0839.2, MA0841.2, MA0843.2, MA0845.1, MA0846.2, MA0847.4, MA0848.1, MA0850.1, MA0852.3, MA0856.1, MA0861.2, MA0863.1, MA0865.3, MA0866.1, MA0867.3, MA0868.3, MA0871.3, MA0872.1, MA0873.2, MA0875.2, MA0876.2, MA0877.4, MA0878.3, MA0882.2, MA0884.2, MA0886.2, MA0887.2, MA0888.2, MA0889.2, MA0890.2, MA0891.2, MA0892.2, MA0893.3, MA0894.2, MA0895.2, MA0899.2, MA0900.3, MA0901.3, MA0902.3, MA0903.2, MA0904.3, MA0905.2, MA0906.2, MA0907.2, MA0908.2, MA0910.3, MA0912.2, MA0913.3, MA0914.2, MA1099.3, MA1100.3, MA1101.3, MA1102.3, MA1103.3, MA1104.3, MA1105.3, MA1106.2, MA1107.3, MA1108.3, MA1109.2, MA1111.2, MA1112.3, MA1114.2, MA1116.2, MA1117.2, MA1118.2, MA1119.2, MA1120.2, MA1121.2, MA1122.2, MA1123.3, MA1124.1, MA1150.2, MA1151.2, MA1152.2, MA1154.2, MA1155.1, MA1419.2, MA1420.1, MA1463.2, MA1464.2, MA1468.1, MA1470.2, MA1471.2, MA1473.2, MA1474.2, MA1475.2, MA1478.2, MA1479.2, MA1480.2, MA1481.2, MA1485.1, MA1487.3, MA1489.1, MA1491.3, MA1493.1, MA1495.2, MA1496.2, MA1497.2, MA1498.3, MA1499.2, MA1500.2, MA1501.2, MA1502.2, MA1503.2, MA1504.2, MA1505.2, MA1506.2, MA1507.2, MA1508.2, MA1509.1, MA1511.2, MA1512.2, MA1514.2, MA1515.2, MA1516.2, MA1517.2, MA1519.2, MA1520.2, MA1521.2, MA1522.2, MA1523.2, MA1527.2, MA1529.2, MA1530.2, MA1531.2, MA1532.2, MA1533.2, MA1534.2, MA1535.2, MA1536.2, MA1539.1, MA1541.2, MA1542.2, MA1544.2, MA1545.2, MA1546.2, MA1547.2, MA1548.2, MA1549.2, MA1550.2, MA1552.2, MA1553.2, MA1554.2, MA1556.1, MA1557.1, MA1558.2, MA1559.2, MA1560.2, MA1561.2, MA1562.2, MA1563.2, MA1564.2, MA1565.2, MA1568.2, MA1569.2, MA1570.1, MA1571.1, MA1572.1, MA1577.2, MA1578.2, MA1579.2, MA1580.1, MA1581.2, MA1584.2, MA1585.2, MA1587.1, MA1588.1, MA1589.2, MA1592.2, MA1594.1, MA1596.1, MA1597.1, MA1599.2, MA1600.2, MA1601.2, MA1630.3, MA1631.2, MA1632.2, MA1633.2, MA1634.2, MA1635.2, MA1636.2, MA1637.2, MA1638.2, MA1639.2, MA1640.2, MA1641.2, MA1642.2, MA1643.2, MA1645.2, MA1646.2, MA1648.2, MA1650.2, MA1651.2, MA1652.2, MA1654.2, MA1655.2, MA1656.2, MA1657.2, MA1683.2, MA1707.2, MA1708.2, MA1709.2, MA1710.2, MA1711.2, MA1712.2, MA1713.2, MA1714.2, MA1717.2, MA1718.1, MA1719.2, MA1721.2, MA1722.2, MA1725.2, MA1726.2, MA1727.2, MA1728.2, MA1729.2, MA1730.2, MA1928.2, MA1929.2, MA1930.2, MA1951.2, MA1959.2, MA1961.2, MA1963.2, MA1964.2, MA1965.2, MA1969.2, MA1970.2, MA1971.2, MA1972.1, MA1973.2, MA1974.2, MA1975.2, MA1976.2, MA1977.2, MA1978.2, MA1979.2, MA1980.1, MA1981.2, MA1982.2, MA1983.2, MA1984.2, MA1985.1, MA1986.2, MA1987.2, MA2003.2, MA2093.1, MA2094.1, MA2096.1, MA2097.1, MA2098.1, MA2099.1, MA2100.1, MA2101.1, MA2118.1, MA2119.1, MA2120.1, MA2121.1, MA2324.1, MA2325.1, MA2326.1, MA2327.1, MA2328.1, MA2330.1, MA2331.1, MA2332.1, MA2334.1, MA2336.1, MA2341.1

INFO [2026-02-02 14:03:31] Running the pipeline for 60 TF in total.

INFO [2026-02-02 14:03:31] Finished successfully. Execution time: 18.9 secs

INFO [2026-02-02 14:03:31] Overlap peaks and TFBS using 2 cores. This may take a while, particularly if the number of samples is large...

WARN [2026-02-02 14:03:31] overlapPeaksAndTFBS: For TFs from JASPAR, only 1 core can currently be utilized for this function instead of the user-provided value of 2.
This warning may or may not be ignored. Carefully check its significance and whether it may affect the results.


Warning message in .checkAndLogWarningsAndErrors(NULL, message, isWarning = TRUE):
"overlapPeaksAndTFBS: For TFs from JASPAR, only 1 core can currently be utilized for this function instead of the user-provided value of 2.
This warning may or may not be ignored. Carefully check its significance and whether it may affect the results.
"
INFO [2026-02-02 14:04:02] Finished successfully. Execution time: 30.2 secs

INFO [2026-02-02 14:04:02]
real data


INFO [2026-02-02 14:04:02] Calculate TF-peak links for connection type expression

INFO [2026-02-02 14:04:02]  Correlate expression and peak counts

INFO [2026-02-02 14:04:02]   Retain 52 unique genes from TF/gene data out of 1995 (filter 1943 non-TF genes and 0 TF genes with 0 counts throughout).

INFO [2026-02-02 14:04:02]   Correlate TF/gene data for 52 unique Ensembl IDs (TFs) and peak counts for 31555 peaks.

INFO [2026-02-02 14:04:02]   Note: For subsequent steps, the same gene may be associated with multiple TF, depending on the translation table.

INFO [2026-02-02 14:04:02]   Finished successfully. Execution time: 0.2 secs

INFO [2026-02-02 14:04:02]  Run FDR calculations for 60 TFs for which TFBS predictions and expression data for the corresponding gene are available.


# Analysis

In [ ]:
GRN <- filterGRNAndConnectGenes(GRN, 
                                TF_peak.fdr.threshold = 1, 
                                peak_gene.fdr.threshold = 1)

results_df <- getGRNConnections(GRN)

write.csv(results_df, paste0(data_path, "GRaNIE_Full_Links.csv"), row.names = FALSE)
# # tf_region_df <- results_df %>%
# #   dplyr::select(TF.name, TF.ENSEMBL, peak.ID, TF_peak.r, TF_peak.fdr) %>%
# #   dplyr::distinct() # 去重，因为一个 TF-Peak 组合可能对应多个靶基因

# # head(tf_region_df)
# GRN

INFO [2026-02-02 14:05:30] Filter GRN network

INFO [2026-02-02 14:05:30]

real data

INFO [2026-02-02 14:05:30] Inital number of rows left before all filtering steps: 152

INFO [2026-02-02 14:05:30]  Filter network and retain only rows with TF-peak connections with an FDR < 1

INFO [2026-02-02 14:05:30]   Number of TF-peak rows before filtering TFs: 152

INFO [2026-02-02 14:05:30]   Number of TF-peak rows after filtering TFs: 152

INFO [2026-02-02 14:05:30] 2. Filter peak-gene connections

INFO [2026-02-02 14:05:30] 3. Merging TF-peak with peak-gene connections and filter the combined table...

INFO [2026-02-02 14:05:30] Inital number of rows left before filtering steps: 257

INFO [2026-02-02 14:05:30]  Filter TF-TF self-loops

INFO [2026-02-02 14:05:30]   Number of rows before filtering genes: 257

INFO [2026-02-02 14:05:30]   Number of rows after filtering genes: 250

INFO [2026-02-02 14:05:30]  Filter network and retain only rows with peak_gene.r in the following interval: (0 - 1]

INFO [2026-02-02 14:05:30]   Number of rows before filtering: 250

INFO [2026-02-02 14:05:30]   Number of rows after filtering: 128

INFO [2026-02-02 14:05:30]  Calculate FDR based on remaining rows, filter network and retain only rows with peak-gene connections with an FDR < 1

INFO [2026-02-02 14:05:30]   Number of rows before filtering genes (including/excluding NA): 128/127

INFO [2026-02-02 14:05:30]   Number of rows after filtering genes (including/excluding NA): 128/127

INFO [2026-02-02 14:05:30] Final number of rows left after all filtering steps: 128

INFO [2026-02-02 14:05:30]

permuted data

INFO [2026-02-02 14:05:30] Inital number of rows left before all filtering steps: 70

INFO [2026-02-02 14:05:30]  Filter network and retain only rows with TF-peak connections with an FDR < 1

INFO [2026-02-02 14:05:30]   Number of TF-peak rows before filtering TFs: 70

INFO [2026-02-02 14:05:30]   Number of TF-peak rows after filtering TFs: 70

INFO [2026-02-02 14:05:30] 2. Filter peak-gene connections

INFO [2026-02-02 14:05:30] 3. Merging TF-peak with peak-gene connections and filter the combined table...

INFO [2026-02-02 14:05:30] Inital number of rows left before filtering steps: 129

INFO [2026-02-02 14:05:30]  Filter TF-TF self-loops

INFO [2026-02-02 14:05:30]   Number of rows before filtering genes: 129

INFO [2026-02-02 14:05:30]   Number of rows after filtering genes: 128

INFO [2026-02-02 14:05:30]  Filter network and retain only rows with peak_gene.r in the following interval: (0 - 1]

INFO [2026-02-02 14:05:30]   Number of rows before filtering: 128

INFO [2026-02-02 14:05:30]   Number of rows after filtering: 64

INFO [2026-02-02 14:05:30]  Calculate FDR based on remaining rows, filter network and retain only rows with peak-gene connections with an FDR < 1

INFO [2026-02-02 14:05:30]   Number of rows before filtering genes (including/excluding NA): 64/63

INFO [2026-02-02 14:05:30]   Number of rows after filtering genes (including/excluding NA): 64/63

INFO [2026-02-02 14:05:30] Final number of rows left after all filtering steps: 64

INFO [2026-02-02 14:05:30]  Finished successfully. Execution time: 0.2 secs

    TF.ID    TF.name TF.ENSEMBL      peak.ID                   TF_peak.r_bin
1   MA0101.1 REL     ENSG00000162924 chr1:37793478-37794775    (-0.45,-0.4]
2   MA0101.1 REL     ENSG00000162924 chr12:132955270-132956649 (-0.4,-0.35]
3   MA0101.1 REL     ENSG00000162924 chr15:90249266-90249826   (-0.4,-0.35]
4   MA0101.1 REL     ENSG00000162924 chr16:27624867-27625626   (-0.4,-0.35]
5   MA0101.1 REL     ENSG00000162924 chr16:85798374-85800492   (-0.4,-0.35]
6   MA0101.1 REL     ENSG00000162924 chr17:75876194-75878942   (-0.4,-0.35]
7   MA0101.1 REL     ENSG00000162924 chr2:219176329-219177316  (-0.4,-0.35]
8   MA0101.1 REL     ENSG00000162924 chr2:219176329-219177316  (-0.4,-0.35]
9   MA0101.1 REL     ENSG00000162924 chr2:72886978-72889172    (-0.4,-0.35]
10  MA0101.1 REL     ENSG00000162924 chr7:6385306-6386140      (-0.4,-0.35]
11  MA0105.4 NFKB1   ENSG00000109320 chr1:35769253-35770297    [0.45,0.5)
12  MA0105.4 NFKB1   ENSG00000109320 chr1:35769253-35770297    [0.45,0.5)
13  MA0105.4 NFKB1   ENSG00000109320 chr2:201465061-201465962  [0.45,0.5)
14  MA0795.1 SMAD3   ENSG00000166949 chr1:100463812-100464384  [0.45,0.5)
15  MA0795.1 SMAD3   ENSG00000166949 chr22:28891986-28892843   (-0.5,-0.45]
16  MA0797.1 TGIF2   ENSG00000118707 chr19:2151121-2152119     [0.55,0.6)
17  MA0801.1 MGA     ENSG00000174197 chr22:46162319-46163103   [0.45,0.5)
18  MA0801.1 MGA     ENSG00000174197 chr22:46162319-46163103   [0.45,0.5)
19  MA1538.1 NR2F1   ENSG00000175745 chr16:20697165-20698081   [0.5,0.55)
20  MA1538.1 NR2F1   ENSG00000175745 chr8:391656-393392        [0.5,0.55)
21  MA1538.1 NR2F1   ENSG00000175745 chr3:129343775-129344777  (-0.55,-0.5]
22  MA0079.5 SP1     ENSG00000185591 chr12:121352066-121352888 (-0.5,-0.45]
23  MA0079.5 SP1     ENSG00000185591 chr19:12800955-12802297   (-0.5,-0.45]
24  MA0079.5 SP1     ENSG00000185591 chr2:215435554-215436752  (-0.5,-0.45]
25  MA0079.5 SP1     ENSG00000185591 chr8:140456988-140458333  (-0.5,-0.45]
26  MA0079.5 SP1     ENSG00000185591 chr9:121764714-121765486  (-0.5,-0.45]
27  MA1466.2 ATF6    ENSG00000118217 chr16:89873070-89874575   (-0.5,-0.45]
28  MA1466.2 ATF6    ENSG00000118217 chr16:89873070-89874575   (-0.5,-0.45]
29  MA0834.2 ATF7    ENSG00000170653 chr16:50741524-50742506   (-0.55,-0.5]
30  MA0834.2 ATF7    ENSG00000170653 chr16:50741524-50742506   (-0.55,-0.5]
⋮   ⋮        ⋮       ⋮               ⋮                         ⋮
99  MA0746.3 SP3     ENSG00000172845 chr9:127734666-127735573  (-0.55,-0.5]
100 MA1574.2 THRB    ENSG00000151090 chr9:33446673-33448230    [0.55,0.6)
101 MA1574.2 THRB    ENSG00000151090 chr9:33446673-33448230    [0.55,0.6)
102 MA1576.2 THRB    ENSG00000151090 chr5:138491765-138493909  (-0.5,-0.45]
103 MA0093.4 USF1    ENSG00000158773 chr16:15052035-15052636   [0.4,0.45)
104 MA0093.4 USF1    ENSG00000158773 chr2:27763193-27763955    [0.4,0.45)
105 MA0844.2 XBP1    ENSG00000100219 chrX:153793881-153795134  [0.45,0.5)
106 MA0844.2 XBP1    ENSG00000100219 chrX:153793881-153795134  [0.45,0.5)
107 MA0844.2 XBP1    ENSG00000100219 chr10:119650941-119652623 (-0.45,-0.4]
108 MA0844.2 XBP1    ENSG00000100219 chr10:119650941-119652623 (-0.45,-0.4]
109 MA0844.2 XBP1    ENSG00000100219 chr10:119650941-119652623 (-0.45,-0.4]
110 MA0844.2 XBP1    ENSG00000100219 chr13:29594482-29596085   (-0.45,-0.4]
111 MA0844.2 XBP1    ENSG00000100219 chr15:74872771-74873886   (-0.4,-0.35]
112 MA0844.2 XBP1    ENSG00000100219 chr21:42724323-42724803   (-0.4,-0.35]
113 MA0844.2 XBP1    ENSG00000100219 chr21:42724323-42724803   (-0.4,-0.35]
114 MA0844.2 XBP1    ENSG00000100219 chr3:183447231-183447960  (-0.4,-0.35]
115 MA0844.2 XBP1    ENSG00000100219 chr3:183447231-183447960  (-0.4,-0.35]
116 MA0844.2 XBP1    ENSG00000100219 chr4:76830731-76832309    (-0.4,-0.35]
117 MA0844.2 XBP1    ENSG00000100219 chr6:20402767-20403910    (-0.5,-0.45]
118 MA0750.3 ZBTB7A  ENSG00000178951 chr19:49127896-49128523   (-0.45,-0.4]
119 MA0750.3 ZBTB7A  ENSG00000178951 chr3:9749393-9751001      (-0.45,-0.4]
120 MA1653.2 ZNF148  ENSG00000163848 chr1:182839140-182840103  (-0.45,-0.4]
121 MA1125.2 ZNF384  ENSG00000126746 chr16:85220214-85220831   [0.5,0.55)
122 MA1125.2 ZNF384  ENSG00000126746 chr20:19886037-19886807   [0.5,0.55)
123 MA1716.2 ZNF76   ENSG00000065029 chr6:29847839-29848462    [0.65,0.7)
124 MA1716.2 ZNF76   ENSG00000065029 chr1:11099228-11100160    (-0.45,-0.4]
125 MA1716.2 ZNF76   ENSG00000065029 chr1:11099228-11100160    (-0.45,-0.4]
126 MA1716.2 ZNF76   ENSG00000065029 chr14:94593616-94594529   (-0.5,-0.45]
127 MA1716.2 ZNF76   ENSG00000065029 chr19:8630967-8631946     (-0.45,-0.4]
128 MA1716.2 ZNF76   ENSG00000065029 chr2:241314848-241316588  (-0.45,-0.4]
    TF_peak.r  TF_peak.fdr TF_peak.fdr_direction TF_peak.connectionType
1   -0.4023783 0.28824763  neg                   expression
2   -0.3811631 0.29021487  neg                   expression
3   -0.3561285 0.29021487  neg                   expression
4   -0.3583290 0.29021487  neg                   expression
5   -0.3550653 0.29021487  neg                   expression
6   -0.3508926 0.29021487  neg                   expression
7   -0.3610473 0.29021487  neg                   expression
8   -0.3610473 0.29021487  neg                   expression
9   -0.3575796 0.29021487  neg                   expression
10  -0.3804662 0.29021487  neg                   expression
11   0.4796409 0.20194102  pos                   expression
12   0.4796409 0.20194102  pos                   expression
13   0.4749958 0.20194102  pos                   expression
14   0.4727386 0.26318672  pos                   expression
15  -0.4790605 0.09026491  neg                   expression
16   0.5584340 0.06604342  pos                   expression
17   0.4607946 0.25992448  pos                   expression
18   0.4607946 0.25992448  pos                   expression
19   0.5177815 0.19634902  pos                   expression
20   0.5482238 0.19634902  pos                   expression
21  -0.5195797 0.00000000  neg                   expression
22  -0.4619338 0.10780096  neg                   expression
23  -0.4897352 0.10780096  neg                   expression
24  -0.4657873 0.10780096  neg                   expression
25  -0.4502135 0.10780096  neg                   expression
26  -0.4832942 0.10780096  neg                   expression
27  -0.4619621 0.18388104  neg                   expression
28  -0.4619621 0.18388104  neg                   expression
29  -0.5066973 0.00000000  neg                   expression
30  -0.5066973 0.00000000  neg                   expression
⋮   ⋮          ⋮           ⋮                     ⋮
99  -0.5063191 0.1864350   neg                   expression
100  0.5604675 0.0000000   pos                   expression
101  0.5604675 0.0000000   pos                   expression
102 -0.4555499 0.1708052   neg                   expression
103  0.4236246 0.2736429   pos                   expression
104  0.4074406 0.2736429   pos                   expression
105  0.4655715 0.1738626   pos                   expression
106  0.4655715 0.1738626   pos                   expression
107 -0.4393875 0.1669658   neg                   expression
108 -0.4393875 0.1669658   neg                   expression
109 -0.4393875 0.1669658   neg                   expression
110 -0.4076755 0.1669658   neg                   expression
111 -0.3655070 0.2160506   neg                   expression
112 -0.3667091 0.2160506   neg                   expression
113 -0.3667091 0.2160506   neg                   expression
114 -0.3935920 0.2160506   neg                   expression
115 -0.3935920 0.2160506   neg                   expression
116 -0.3888358 0.2160506   neg                   expression
117 -0.4709567 0.1306791   neg                   expression
118 -0.4083112 0.1689201   neg                   expression
119 -0.4112968 0.1689201   neg                   expression
120 -0.4120594 0.2279884   neg                   expression
121  0.5145387 0.1691584   pos                   expression
122  0.5143357 0.1691584   pos                   expression
123  0.6794914 0.0000000   pos                   expression
124 -0.4061031 0.1407496   neg                   expression
125 -0.4061031 0.1407496   neg                   expression
126 -0.4655699 0.0000000   neg                   expression
127 -0.4177778 0.1407496   neg                   expression
128 -0.4099663 0.1407496   neg                   expression
    peak_gene.source peak_gene.distance peak_gene.r peak_gene.p_raw
1   neighborhood          0             0.02446782  0.8660619
2   neighborhood      29716             0.08231550  0.5698296
3   neighborhood     138416             0.13259588  0.3586492
4   neighborhood     165313             0.19077131  0.1844878
5   neighborhood          0             0.06967765  0.6306453
6   neighborhood       1393             0.20409447  0.1551197
7   neighborhood       4433             0.02515632  0.8623290
8   neighborhood        105             0.15111923  0.2948331
9   neighborhood      52864             0.01984034  0.8912226
10  neighborhood      59813             0.14694765  0.3085179
11  neighborhood     211781             0.04386409  0.7622964
12  neighborhood      37719             0.05102358  0.7249169
13  neighborhood      87855             0.07643096  0.5978105
14  neighborhood     197597             0.17814042  0.2158231
15  neighborhood      97432             0.18154227  0.2070407
16  neighborhood      11814             0.02544278  0.8607767
17  neighborhood     104858             0.21663846  0.1307555
18  neighborhood     167772             0.11266883  0.4359658
19  neighborhood     201787             0.29483449  0.0376619
20  neighborhood      96411             0.19967236  0.1644588
21  neighborhood      64948             0.13809369  0.3388881
22  neighborhood     114392             0.09136801  0.5280075
23  neighborhood       9470             0.05546403  0.7020423
24  neighborhood     123599             0.18203439  0.2057913
25  neighborhood      61823             0.30345422  0.0321716
26  neighborhood     197658             0.11960814  0.4080434
27  neighborhood     152671             0.09518206  0.5108524
28  neighborhood     146388             0.11866317  0.4117839
29  neighborhood     193129             0.15775549  0.2738873
30  neighborhood          0             0.04845107  0.7382801
⋮   ⋮                ⋮                  ⋮           ⋮
99  neighborhood      59024             0.10467158  0.46942779
100 neighborhood     198854             0.08259077  0.56853569
101 neighborhood      13123             0.16265315  0.25907650
102 neighborhood     159831             0.06204801  0.66860638
103 neighborhood     218315             0.07699636  0.59509595
104 neighborhood     112385             0.10559078  0.46551318
105 neighborhood      29686             0.29106716  0.04029277
106 neighborhood     152423             0.18997979  0.18634993
107 neighborhood          0             0.05035156  0.72840020
108 neighborhood      73419             0.01598310  0.91227772
109 neighborhood     176781             0.12657215  0.38108805
110 neighborhood      85069             0.08833938  0.54182933
111 neighborhood      16119             0.17003368  0.23778965
112 neighborhood     118291             0.05205790  0.71956656
113 neighborhood     154841             0.16137604  0.26288570
114 neighborhood     187650             0.11049326  0.44493441
115 neighborhood     249837             0.06126117  0.67257047
116 neighborhood     214846             0.04831720  0.73897767
117 neighborhood        889             0.06816573  0.63809712
118 neighborhood      42478             0.06139319  0.67190476
119 neighborhood      99961             0.19458452  0.17570346
120 neighborhood     183317             0.02800191  0.84693304
121 neighborhood      50690             0.06941285  0.63194779
122 neighborhood     130503             0.18077890  0.20898927
123 neighborhood     218247             0.22953335  0.10882763
124 neighborhood      86885             0.18791717  0.19126562
125 neighborhood      32611             0.06152882  0.67122109
126 neighborhood     216870                     NA          NA
127 neighborhood     240987             0.12808242  0.37538530
128 neighborhood     126340             0.03574397  0.80534625
    peak_gene.p_adj gene.ENSEMBL    gene.name gene.type
1   0.9532171       ENSG00000185090 MANEAL    protein_coding
2   0.9532171       ENSG00000198393 ZNF26     protein_coding
3   0.9432333       ENSG00000140575 IQGAP1    protein_coding
4   0.9432333       ENSG00000077235 GTF3C1    protein_coding
5   0.9532171       ENSG00000131143 COX4I1    protein_coding
6   0.9432333       ENSG00000141569 TRIM65    protein_coding
7   0.9532171       ENSG00000115649 CNPPD1    protein_coding
8   0.9432333       ENSG00000144567 RETREG2   protein_coding
9   0.9532171       ENSG00000144040 SFXN5     protein_coding
10  0.9432333       ENSG00000136240 KDELR2    protein_coding
11  0.9532171       ENSG00000020129 NCDN      protein_coding
12  0.9532171       ENSG00000134698 AGO4      protein_coding
13  0.9532171       ENSG00000115993 TRAK2     protein_coding
14  0.9432333       ENSG00000137996 RTCA      protein_coding
15  0.9432333       ENSG00000100219 XBP1      protein_coding
16  0.9532171       ENSG00000104885 DOT1L     protein_coding
17  0.9432333       ENSG00000075234 TTC38     protein_coding
18  0.9480780       ENSG00000100416 TRMU      protein_coding
19  0.8528637       ENSG00000102897 LYRM1     protein_coding
20  0.9432333       ENSG00000180190 TDRP      protein_coding
21  0.9432333       ENSG00000183624 HMCES     protein_coding
22  0.9532171       ENSG00000110931 CAMKK2    protein_coding
23  0.9532171       ENSG00000171223 JUNB      protein_coding
24  0.9432333       ENSG00000138363 ATIC      protein_coding
25  0.8528637       ENSG00000123908 AGO2      protein_coding
26  0.9432333       ENSG00000136848 DAB2IP    protein_coding
27  0.9532171       ENSG00000158805 ZNF276    protein_coding
28  0.9432333       ENSG00000187741 FANCA     protein_coding
29  0.9432333       ENSG00000140807 NKD1      protein_coding
30  0.9532171       ENSG00000083799 CYLD      protein_coding
⋮   ⋮               ⋮               ⋮         ⋮
99  0.9532171       ENSG00000136877 FPGS      protein_coding
100 0.9532171       ENSG00000107262 BAG1      protein_coding
101 0.9432333       ENSG00000165271 NOL6      protein_coding
102 0.9532171       ENSG00000120709 FAM53C    protein_coding
103 0.9532171       ENSG00000103512 NOMO1     protein_coding
104 0.9532171       ENSG00000119760 SUPT7L    protein_coding
105 0.8528637       ENSG00000198753 PLXNB3    protein_coding
106 0.9432333       ENSG00000172534 HCFC1     protein_coding
107 0.9532171       ENSG00000151929 BAG3      protein_coding
108 0.9532171       ENSG00000198825 INPP5F    protein_coding
109 0.9432333       ENSG00000197771 MCMBP     protein_coding
110 0.9532171       ENSG00000139514 SLC7A1    protein_coding
111 0.9432333       ENSG00000178802 MPI       protein_coding
112 0.9532171       ENSG00000160193 WDR4      protein_coding
113 0.9432333       ENSG00000160194 NDUFV3    protein_coding
114 0.9480780       ENSG00000114796 KLHL24    protein_coding
115 0.9532171       ENSG00000163872 YEATS2    protein_coding
116 0.9532171       ENSG00000118816 CCNI      protein_coding
117 0.9532171       ENSG00000112242 E2F3      protein_coding
118 0.9532171       ENSG00000104852 SNRNP70   protein_coding
119 0.9432333       ENSG00000163719 MTMR14    protein_coding
120 0.9532171       ENSG00000135862 LAMC1     protein_coding
121 0.9532171       ENSG00000131149 GSE1      protein_coding
122 0.9432333       ENSG00000173418 NAA20     protein_coding
123 0.9432333       ENSG00000204619 PPP1R11   protein_coding
124 0.9432333       ENSG00000120948 TARDBP    protein_coding
125 0.9532171       ENSG00000171824 EXOSC10   protein_coding
126        NA       ENSG00000197249 SERPINA1  protein_coding
127 0.9432333       ENSG00000185236 RAB11B    protein_coding
128 0.9532171       ENSG00000146205 ANO7      protein_coding

In [49]:
# # 5. 过滤并生成网络
# # 对于 Metacell 数据，建议先用 0.2 的 FDR 试试水，如果结果太多再收紧到 0.1
# GRN <- filterGRNAndConnectGenes(GRN, TF_peak.fdr.threshold = 0.1,
#                                 peak_gene.fdr.threshold = 0.1)


# # 6. 导出结果
# results_df <- getGRNConnections(GRN, type = "all.filtered")
# # write.csv(results_df, "GRaNIE_Final_Network.csv", row.names = FALSE)

# # 打印结果概览
# print(paste("找到的连接数:", nrow(results_df)))
rownames(results_df)

  [1] "1"   "2"   "3"   "4"   "5"   "6"   "7"   "8"   "9"   "10"  "11"  "12"
 [13] "13"  "14"  "15"  "16"  "17"  "18"  "19"  "20"  "21"  "22"  "23"  "24"
 [25] "25"  "26"  "27"  "28"  "29"  "30"  "31"  "32"  "33"  "34"  "35"  "36"
 [37] "37"  "38"  "39"  "40"  "41"  "42"  "43"  "44"  "45"  "46"  "47"  "48"
 [49] "49"  "50"  "51"  "52"  "53"  "54"  "55"  "56"  "57"  "58"  "59"  "60"
 [61] "61"  "62"  "63"  "64"  "65"  "66"  "67"  "68"  "69"  "70"  "71"  "72"
 [73] "73"  "74"  "75"  "76"  "77"  "78"  "79"  "80"  "81"  "82"  "83"  "84"
 [85] "85"  "86"  "87"  "88"  "89"  "90"  "91"  "92"  "93"  "94"  "95"  "96"
 [97] "97"  "98"  "99"  "100" "101" "102" "103" "104" "105" "106" "107" "108"
[109] "109" "110" "111" "112" "113" "114" "115" "116" "117" "118" "119" "120"
[121] "121" "122" "123" "124" "125" "126" "127" "128"

# Test

## TF-region

In [53]:
tf_region_df <- results_df %>%
  dplyr::select(TF.name, TF.ENSEMBL, peak.ID, TF_peak.r, TF_peak.fdr) %>%
  dplyr::distinct() # 去重，因为一个 TF-Peak 组合可能对应多个靶基因

tf_region_df
write.csv(tf_region_df, paste0(data_path, "GRaNIE_tf_region_Links.csv"), row.names = FALSE)

   TF.name TF.ENSEMBL      peak.ID                   TF_peak.r  TF_peak.fdr
1  REL     ENSG00000162924 chr1:37793478-37794775    -0.4023783 0.28824763
2  REL     ENSG00000162924 chr12:132955270-132956649 -0.3811631 0.29021487
3  REL     ENSG00000162924 chr15:90249266-90249826   -0.3561285 0.29021487
4  REL     ENSG00000162924 chr16:27624867-27625626   -0.3583290 0.29021487
5  REL     ENSG00000162924 chr16:85798374-85800492   -0.3550653 0.29021487
6  REL     ENSG00000162924 chr17:75876194-75878942   -0.3508926 0.29021487
7  REL     ENSG00000162924 chr2:219176329-219177316  -0.3610473 0.29021487
8  REL     ENSG00000162924 chr2:72886978-72889172    -0.3575796 0.29021487
9  REL     ENSG00000162924 chr7:6385306-6386140      -0.3804662 0.29021487
10 NFKB1   ENSG00000109320 chr1:35769253-35770297     0.4796409 0.20194102
11 NFKB1   ENSG00000109320 chr2:201465061-201465962   0.4749958 0.20194102
12 SMAD3   ENSG00000166949 chr1:100463812-100464384   0.4727386 0.26318672
13 SMAD3   ENSG00000166949 chr22:28891986-28892843   -0.4790605 0.09026491
14 TGIF2   ENSG00000118707 chr19:2151121-2152119      0.5584340 0.06604342
15 MGA     ENSG00000174197 chr22:46162319-46163103    0.4607946 0.25992448
16 NR2F1   ENSG00000175745 chr16:20697165-20698081    0.5177815 0.19634902
17 NR2F1   ENSG00000175745 chr8:391656-393392         0.5482238 0.19634902
18 NR2F1   ENSG00000175745 chr3:129343775-129344777  -0.5195797 0.00000000
19 SP1     ENSG00000185591 chr12:121352066-121352888 -0.4619338 0.10780096
20 SP1     ENSG00000185591 chr19:12800955-12802297   -0.4897352 0.10780096
21 SP1     ENSG00000185591 chr2:215435554-215436752  -0.4657873 0.10780096
22 SP1     ENSG00000185591 chr8:140456988-140458333  -0.4502135 0.10780096
23 SP1     ENSG00000185591 chr9:121764714-121765486  -0.4832942 0.10780096
24 ATF6    ENSG00000118217 chr16:89873070-89874575   -0.4619621 0.18388104
25 ATF7    ENSG00000170653 chr16:50741524-50742506   -0.5066973 0.00000000
26 CREB1   ENSG00000118260 chr1:12525289-12526041    -0.5075578 0.00000000
27 ELF2    ENSG00000109381 chr2:118087999-118088874   0.5233922 0.29232525
28 ETV3    ENSG00000117036 chr19:38831072-38832502    0.4149416 0.22103559
29 ETV3    ENSG00000117036 chr3:53072303-53073664     0.4125017 0.22103559
30 ETV3    ENSG00000117036 chr9:92189342-92190132     0.4226774 0.22103559
⋮  ⋮       ⋮               ⋮                         ⋮          ⋮
70 SOX9    ENSG00000125398 chr15:68194957-68195440   -0.5776857 0.1169626
71 SOX9    ENSG00000125398 chr5:68080271-68081166    -0.5962102 0.1169626
72 SP3     ENSG00000172845 chr1:21936764-21937868    -0.5192737 0.1864350
73 SP3     ENSG00000172845 chr1:23799661-23801473    -0.4655246 0.2109526
74 SP3     ENSG00000172845 chr15:84715648-84717023   -0.5042940 0.1864350
75 SP3     ENSG00000172845 chr20:31869967-31870982   -0.4605142 0.2109526
76 SP3     ENSG00000172845 chr7:992331-993625        -0.4657085 0.2109526
77 SP3     ENSG00000172845 chr9:127734666-127735573  -0.5063191 0.1864350
78 THRB    ENSG00000151090 chr9:33446673-33448230     0.5604675 0.0000000
79 THRB    ENSG00000151090 chr5:138491765-138493909  -0.4555499 0.1708052
80 USF1    ENSG00000158773 chr16:15052035-15052636    0.4236246 0.2736429
81 USF1    ENSG00000158773 chr2:27763193-27763955     0.4074406 0.2736429
82 XBP1    ENSG00000100219 chrX:153793881-153795134   0.4655715 0.1738626
83 XBP1    ENSG00000100219 chr10:119650941-119652623 -0.4393875 0.1669658
84 XBP1    ENSG00000100219 chr13:29594482-29596085   -0.4076755 0.1669658
85 XBP1    ENSG00000100219 chr15:74872771-74873886   -0.3655070 0.2160506
86 XBP1    ENSG00000100219 chr21:42724323-42724803   -0.3667091 0.2160506
87 XBP1    ENSG00000100219 chr3:183447231-183447960  -0.3935920 0.2160506
88 XBP1    ENSG00000100219 chr4:76830731-76832309    -0.3888358 0.2160506
89 XBP1    ENSG00000100219 chr6:20402767-20403910    -0.4709567 0.1306791
90 ZBTB7A  ENSG00000178951 chr19:49127896-49128523   -0.4083112 0.1689201
91 ZBTB7A  ENSG00000178951 chr3:9749393-9751001      -0.4112968 0.1689201
92 ZNF148  ENSG00000163848 chr1:182839140-182840103  -0.4120594 0.2279884
93 ZNF384  ENSG00000126746 chr16:85220214-85220831    0.5145387 0.1691584
94 ZNF384  ENSG00000126746 chr20:19886037-19886807    0.5143357 0.1691584
95 ZNF76   ENSG00000065029 chr6:29847839-29848462     0.6794914 0.0000000
96 ZNF76   ENSG00000065029 chr1:11099228-11100160    -0.4061031 0.1407496
97 ZNF76   ENSG00000065029 chr14:94593616-94594529   -0.4655699 0.0000000
98 ZNF76   ENSG00000065029 chr19:8630967-8631946     -0.4177778 0.1407496
99 ZNF76   ENSG00000065029 chr2:241314848-241316588  -0.4099663 0.1407496

## Region-Gene

In [51]:
region_gene_df <- results_df %>%
  dplyr::select(peak.ID, gene.name, gene.ENSEMBL, peak_gene.r, peak_gene.p_adj, peak_gene.distance) %>%
  dplyr::distinct() # 去重，因为一个 Peak-Gene 组合可能被多个 TF 结合

write.csv(region_gene_df, paste0(data_path, "GRaNIE_region_gene_Links.csv"), row.names = FALSE)

  peak.ID                   gene.name gene.ENSEMBL    peak_gene.r
1 chr1:37793478-37794775    MANEAL    ENSG00000185090 0.02446782
2 chr12:132955270-132956649 ZNF26     ENSG00000198393 0.08231550
3 chr15:90249266-90249826   IQGAP1    ENSG00000140575 0.13259588
4 chr16:27624867-27625626   GTF3C1    ENSG00000077235 0.19077131
5 chr16:85798374-85800492   COX4I1    ENSG00000131143 0.06967765
6 chr17:75876194-75878942   TRIM65    ENSG00000141569 0.20409447
  peak_gene.p_adj peak_gene.distance
1 0.9532171            0
2 0.9532171        29716
3 0.9432333       138416
4 0.9432333       165313
5 0.9532171            0
6 0.9432333         1393

## TF-Gene

In [52]:
tf_gene_df <- results_df %>%
  dplyr::select(TF.name, gene.name, peak.ID, TF_peak.r, peak_gene.r)

write.csv(tf_gene_df, paste0(data_path, "GRaNIE_tf_gene_Links.csv"), row.names = FALSE)

  TF.name gene.name peak.ID                   TF_peak.r  peak_gene.r
1 REL     MANEAL    chr1:37793478-37794775    -0.4023783 0.02446782
2 REL     ZNF26     chr12:132955270-132956649 -0.3811631 0.08231550
3 REL     IQGAP1    chr15:90249266-90249826   -0.3561285 0.13259588
4 REL     GTF3C1    chr16:27624867-27625626   -0.3583290 0.19077131
5 REL     COX4I1    chr16:85798374-85800492   -0.3550653 0.06967765
6 REL     TRIM65    chr17:75876194-75878942   -0.3508926 0.20409447