In [1]:
# Load Packages
library(Pando)
library(Seurat)
library(Matrix)
library(data.table)
library(BSgenome.Hsapiens.UCSC.hg38)
library(EnsDb.Hsapiens.v86)
library(Signac)
library(TFBSTools) # 处理 motifs 对象需要
library(GenomeInfoDb) # <--- 新增：必须加载，否则 keepStandardChromosomes 会报错
library(dplyr)
data(motifs)

Loading required package: SeuratObject

Loading required package: sp


Attaching package: ‘SeuratObject’


The following objects are masked from ‘package:Pando’:

    LayerData, VariableFeatures


The following objects are masked from ‘package:base’:

    intersect, t



Attaching package: ‘Seurat’


The following objects are masked from ‘package:Pando’:

    GetAssay, VariableFeatures


Loading required package: GenomeInfoDb

Loading required package: BiocGenerics


Attaching package: ‘BiocGenerics’


The following object is masked from ‘package:SeuratObject’:

    intersect


The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs


The following objects are masked from ‘package:base’:

    anyDuplicated, aperm, append, as.data.frame, basename, cbind,
    colnames, dirname, do.call, duplicated, eval, evalq, Filter, Find,
    get, grep, grepl, intersect, is.unsorted, lapply, Map, mapply,
    match, mget, order, paste, pmax, pmax.int, pmin, pmin.int,
    Position, rank, rbind, Reduce, rownames, sapply, setdiff, sort,
    table, tapply, union, unique, unsplit, which.max, which.min


Loading required package: S4Vectors

Loading required package: stats4


Attaching package: ‘S4Vectors’


The following objects are masked from ‘package:data.table’:

    first, second


The following objects are masked from ‘package:Matrix’:

    expand, unname


The following object is masked from ‘package:utils’:

    findMatches


The following objects are masked from ‘package:base’:

    expand.grid, I, unname


Loading required package: IRanges


Attaching package: ‘IRanges’


The following object is masked from ‘package:data.table’:

    shift


The following object is masked from ‘package:sp’:

    %over%


Loading required package: BSgenome

Loading required package: GenomicRanges

Loading required package: Biostrings

Loading required package: XVector


Attaching package: ‘Biostrings’


The following object is masked from ‘package:base’:

    strsplit


Loading required package: BiocIO

Loading required package: rtracklayer


Attaching package: ‘rtracklayer’


The following object is masked from ‘package:BiocIO’:

    FileForFormat


Loading required package: ensembldb

Loading required package: GenomicFeatures

Loading required package: AnnotationDbi

Loading required package: Biobase

Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.


Loading required package: AnnotationFilter


Attaching package: 'ensembldb'


The following object is masked from 'package:stats':

    filter





Attaching package: 'TFBSTools'


The following object is masked from 'package:Matrix':

    Matrix

In [3]:
cell_type <- "HepG2"

data_path <-paste0("/home/liyang/BioWuYan/dygmamba_project/data/cell_line/", cell_type, "/process/")

output_path <- paste0("/home/liyang/BioWuYan/dygmamba_project/data/cell_line/", cell_type, "/data_pando/")


grn_obj <- readRDS(paste0(output_path,"grn_seurat_object_tt.rds"))

In [22]:
# 1. 提取所有推断出的调控参数
grn_df <- coef(grn_obj)

# 2. 转换为标准的 DataFrame
grn_df <- as.data.frame(grn_df)

grn_significant <- subset(grn_df, padj < 0.05)

tf_gene_df <- grn_significant[, c('tf', 'target', 'estimate', 'padj')]
colnames(tf_gene_df) <- c('TF', 'Gene', 'Weight', 'padj')
tf_gene_df <- tf_gene_df %>% 
  distinct(TF, Gene, .keep_all = TRUE)

tf_region_df <- grn_significant[, c('tf', 'region', 'estimate', 'padj')]
colnames(tf_region_df) <- c('TF', 'Region', 'Weight', 'padj')
tf_region_df <- tf_region_df %>% 
  distinct(TF, Region, .keep_all = TRUE)

region_gene_df <- grn_significant[, c('region', 'target', 'estimate', 'padj')]
colnames(region_gene_df) <- c('Region', 'Gene', 'Weight', 'padj')
region_gene_df <- region_gene_df %>% 
  distinct(Region, Gene, .keep_all = TRUE)

write.csv(tf_gene_df, file = paste0(output_path, "tf_gene_network.csv"), row.names = FALSE)
write.csv(tf_region_df, file = paste0(output_path, "tf_region_network.csv"), row.names = FALSE)
write.csv(region_gene_df, file = paste0(output_path, "region_gene_network.csv"), row.names = FALSE)

In [ ]:

# 依据 term (TF) 和 region (Peak) 删除重复

原始行数: 105

去重后行数: 105

In [16]:
tf_gene_df
tf_region_df
region_gene_df

     TF      Gene     Weight      padj
109  ZNF292  CDC25B    0.22729104 0.012731249
196  MZF1    SRC       0.12554847 0.021478433
288  FOXP4   TAF4     -0.21165794 0.024474163
462  ATF7    RERE     -0.57530693 0.009165318
541  ZFP64   FUCA1     0.30105550 0.019712886
554  RARA    DHDDS    -0.10380162 0.021859901
601  ZNF689  MARCKSL1 -0.27367482 0.014161315
612  ZNF765  PHC2     -0.26775717 0.010730838
675  REPIN1  BTBD19    0.10130549 0.040474106
683  MZF1    LRRC41    0.38484789 0.011462763
686  ZNF765  LRRC41    0.18923642 0.011177257
703  NFYC    OSBPL9   -0.28124748 0.036654755
818  ZNF516  DENND4B  -0.08310465 0.011172776
819  ZFX     ADAR     -0.07396980 0.005359277
900  ZNF516  GAS5      0.16661119 0.026803195
902  IRF3    GAS5     -0.25720136 0.016912332
945  IRF3    BPNT1     0.39529130 0.043722917
1080 TOX3    BAG6     -0.12461709 0.003121909
1087 NFYC    BAG6     -0.05303682 0.011459781
1132 E2F3    RPS18    -0.26207479 0.034826751
1135 ZNF33B  ZNF76     0.48808103 0.023198439
1187 ZFPM1   PTCHD4   -0.18748370 0.034078917
1353 SP1     RPUSD3    0.04432472 0.048035531
1377 ZNF275  TGFBR2   -0.26745924 0.019411317
1425 NFATC2  IFRD2     0.09597941 0.027592001
1494 ZNF317  KLF15     0.23170750 0.013250029
1584 JUNB    LPP       0.21202126 0.033979261
1628 RARA    MICALL2   0.21797271 0.044813657
1629 RARA    MICALL2   0.05259880 0.026288632
1661 ZNF697  TOMM7     0.64151660 0.032513348
⋮    ⋮       ⋮        ⋮           ⋮
4270 ARID3A  AGO2     -0.10157370 4.021178e-02
4274 FOXM1   AGO2      0.11284978 4.851016e-02
4283 GATA4   AGO2     -0.12885647 2.435994e-05
4335 CREB1   SLC39A4  -0.11065245 1.530717e-02
4338 TERF2   SLC39A4   0.05725429 4.921562e-02
4353 ZNF765  RECQL4   -0.15830958 3.158203e-02
4527 ZKSCAN8 CD320     0.06001303 4.644272e-02
4663 FOXM1   ZNF780B   0.65233395 3.531347e-02
4737 TCF3    BBC3      0.21448731 4.325234e-02
4755 HMGB2   NUCB1    -0.31783261 3.864608e-02
4758 ZKSCAN8 RPS11    -0.47628430 3.007123e-03
5032 ZNF516  RABL6    -0.41609221 3.717158e-02
5202 ZNF275  MCF2L    -0.18649791 5.900777e-03
5204 HMGB2   F10       0.16108259 3.665475e-02
5225 GATA4   HOMEZ     0.33680574 8.483196e-03
5267 ZNF117  TRAPPC6B  0.36383948 1.169085e-03
5278 ZNF76   RPS29    -0.25962276 3.907691e-02
5310 NFIX    SIX4      0.30093247 1.809534e-03
5329 ZFPM1   ZFYVE26   0.20922847 4.987006e-03
5541 FOXP4   HINT1    -0.04373167 1.475161e-02
5613 IRF3    CLTB      0.09470763 8.660884e-03
5674 NFKB1   CSNK1E    0.24324441 1.102857e-02
5677 NFKB1   CSNK1E    0.19733548 2.335109e-02
5708 THAP11  PRR5      0.23015375 4.105594e-02
5814 THRB    SGMS1     0.47685645 1.694983e-02
5920 ZBTB7A  ABCC2    -0.06097351 2.679541e-02
5937 JUNB    SH3PXD2A -0.23896955 3.167467e-02
6154 ZNF516  IGDCC3   -0.09185287 3.163917e-02
6190 ZNF768  IDH3A     0.21828503 4.767480e-02
6217 NFIX    KIF7      0.19661652 2.239187e-02

     TF      Region                    Weight      padj
109  ZNF292  chr20-3739193-3740578      0.22729104 0.012731249
196  MZF1    chr20-37332031-37332630    0.12554847 0.021478433
288  FOXP4   chr20-62104409-62104736   -0.21165794 0.024474163
462  ATF7    chr1-8626029-8627024      -0.57530693 0.009165318
541  ZFP64   chr1-23765494-23766246     0.30105550 0.019712886
554  RARA    chr1-26350735-26352137    -0.10380162 0.021859901
601  ZNF689  chr1-32338424-32338916    -0.27367482 0.014161315
612  ZNF765  chr1-33347083-33347860    -0.26775717 0.010730838
675  REPIN1  chr1-44793273-44794296     0.10130549 0.040474106
683  MZF1    chr1-46179610-46180479     0.38484789 0.011462763
686  ZNF765  chr1-46301651-46303123     0.18923642 0.011177257
703  NFYC    chr1-51647964-51648710    -0.28124748 0.036654755
818  ZNF516  chr1-153963704-153964148  -0.08310465 0.011172776
819  ZFX     chr1-154558634-154558907  -0.07396980 0.005359277
900  ZNF516  chr1-173916674-173917218   0.16661119 0.026803195
902  IRF3    chr1-173917379-173918318  -0.25720136 0.016912332
945  IRF3    chr1-220121920-220122341   0.39529130 0.043722917
1080 TOX3    chr6-31598296-31598863    -0.12461709 0.003121909
1087 NFYC    chr6-31739764-31739947    -0.05303682 0.011459781
1132 E2F3    chr6-33172638-33173059    -0.26207479 0.034826751
1135 ZNF33B  chr6-35241267-35241542     0.48808103 0.023198439
1187 ZFPM1   chr6-48110966-48111702    -0.18748370 0.034078917
1353 SP1     chr3-9933631-9933821       0.04432472 0.048035531
1377 ZNF275  chr3-30518267-30518752    -0.26745924 0.019411317
1425 NFATC2  chr3-50264426-50265267     0.09597941 0.027592001
1494 ZNF317  chr3-126389081-126389879   0.23170750 0.013250029
1584 JUNB    chr3-188294734-188295491   0.21202126 0.033979261
1628 RARA    chr7-1431564-1432882       0.21797271 0.044813657
1629 RARA    chr7-1458930-1459183       0.05259880 0.026288632
1661 ZNF697  chr7-22879727-22880137     0.64151660 0.032513348
⋮    ⋮       ⋮                         ⋮           ⋮
4270 ARID3A  chr8-140437567-140438316  -0.10157370 4.021178e-02
4274 FOXM1   chr8-140464007-140465094   0.11284978 4.851016e-02
4283 GATA4   chr8-140625817-140626484  -0.12885647 2.435994e-05
4335 CREB1   chr8-144373261-144373809  -0.11065245 1.530717e-02
4338 TERF2   chr8-144503126-144503736   0.05725429 4.921562e-02
4353 ZNF765  chr8-144518042-144518370  -0.15830958 3.158203e-02
4527 ZKSCAN8 chr19-8390457-8390985      0.06001303 4.644272e-02
4663 FOXM1   chr19-40084911-40085305    0.65233395 3.531347e-02
4737 TCF3    chr19-47313095-47313655    0.21448731 4.325234e-02
4755 HMGB2   chr19-48907701-48908183   -0.31783261 3.864608e-02
4758 ZKSCAN8 chr19-49422643-49422743   -0.47628430 3.007123e-03
5032 ZNF516  chr9-136777077-136777675  -0.41609221 3.717158e-02
5202 ZNF275  chr13-113022287-113024304 -0.18649791 5.900777e-03
5204 HMGB2   chr13-113022287-113024304  0.16108259 3.665475e-02
5225 GATA4   chr14-23186887-23187657    0.33680574 8.483196e-03
5267 ZNF117  chr14-39185741-39186661    0.36383948 1.169085e-03
5278 ZNF76   chr14-49586417-49587081   -0.25962276 3.907691e-02
5310 NFIX    chr14-60625180-60625953    0.30093247 1.809534e-03
5329 ZFPM1   chr14-67738788-67739355    0.20922847 4.987006e-03
5541 FOXP4   chr5-131171039-131171605  -0.04373167 1.475161e-02
5613 IRF3    chr5-176388976-176389330   0.09470763 8.660884e-03
5674 NFKB1   chr22-38218517-38219218    0.24324441 1.102857e-02
5677 NFKB1   chr22-38261003-38262764    0.19733548 2.335109e-02
5708 THAP11  chr22-44668267-44668546    0.23015375 4.105594e-02
5814 THRB    chr10-50550411-50550777    0.47685645 1.694983e-02
5920 ZBTB7A  chr10-99732101-99732219   -0.06097351 2.679541e-02
5937 JUNB    chr10-103645252-103646270 -0.23896955 3.167467e-02
6154 ZNF516  chr15-65400947-65401783   -0.09185287 3.163917e-02
6190 ZNF768  chr15-78108363-78108754    0.21828503 4.767480e-02
6217 NFIX    chr15-89647075-89647595    0.19661652 2.239187e-02

     Region                    Gene     Weight      padj
109  chr20-3739193-3740578     CDC25B    0.22729104 0.012731249
196  chr20-37332031-37332630   SRC       0.12554847 0.021478433
288  chr20-62104409-62104736   TAF4     -0.21165794 0.024474163
462  chr1-8626029-8627024      RERE     -0.57530693 0.009165318
541  chr1-23765494-23766246    FUCA1     0.30105550 0.019712886
554  chr1-26350735-26352137    DHDDS    -0.10380162 0.021859901
601  chr1-32338424-32338916    MARCKSL1 -0.27367482 0.014161315
612  chr1-33347083-33347860    PHC2     -0.26775717 0.010730838
675  chr1-44793273-44794296    BTBD19    0.10130549 0.040474106
683  chr1-46179610-46180479    LRRC41    0.38484789 0.011462763
686  chr1-46301651-46303123    LRRC41    0.18923642 0.011177257
703  chr1-51647964-51648710    OSBPL9   -0.28124748 0.036654755
818  chr1-153963704-153964148  DENND4B  -0.08310465 0.011172776
819  chr1-154558634-154558907  ADAR     -0.07396980 0.005359277
900  chr1-173916674-173917218  GAS5      0.16661119 0.026803195
902  chr1-173917379-173918318  GAS5     -0.25720136 0.016912332
945  chr1-220121920-220122341  BPNT1     0.39529130 0.043722917
1080 chr6-31598296-31598863    BAG6     -0.12461709 0.003121909
1087 chr6-31739764-31739947    BAG6     -0.05303682 0.011459781
1132 chr6-33172638-33173059    RPS18    -0.26207479 0.034826751
1135 chr6-35241267-35241542    ZNF76     0.48808103 0.023198439
1187 chr6-48110966-48111702    PTCHD4   -0.18748370 0.034078917
1353 chr3-9933631-9933821      RPUSD3    0.04432472 0.048035531
1377 chr3-30518267-30518752    TGFBR2   -0.26745924 0.019411317
1425 chr3-50264426-50265267    IFRD2     0.09597941 0.027592001
1494 chr3-126389081-126389879  KLF15     0.23170750 0.013250029
1584 chr3-188294734-188295491  LPP       0.21202126 0.033979261
1628 chr7-1431564-1432882      MICALL2   0.21797271 0.044813657
1629 chr7-1458930-1459183      MICALL2   0.05259880 0.026288632
1661 chr7-22879727-22880137    TOMM7     0.64151660 0.032513348
⋮    ⋮                         ⋮        ⋮           ⋮
4270 chr8-140437567-140438316  AGO2     -0.10157370 4.021178e-02
4274 chr8-140464007-140465094  AGO2      0.11284978 4.851016e-02
4283 chr8-140625817-140626484  AGO2     -0.12885647 2.435994e-05
4335 chr8-144373261-144373809  SLC39A4  -0.11065245 1.530717e-02
4338 chr8-144503126-144503736  SLC39A4   0.05725429 4.921562e-02
4353 chr8-144518042-144518370  RECQL4   -0.15830958 3.158203e-02
4527 chr19-8390457-8390985     CD320     0.06001303 4.644272e-02
4663 chr19-40084911-40085305   ZNF780B   0.65233395 3.531347e-02
4737 chr19-47313095-47313655   BBC3      0.21448731 4.325234e-02
4755 chr19-48907701-48908183   NUCB1    -0.31783261 3.864608e-02
4758 chr19-49422643-49422743   RPS11    -0.47628430 3.007123e-03
5032 chr9-136777077-136777675  RABL6    -0.41609221 3.717158e-02
5202 chr13-113022287-113024304 MCF2L    -0.18649791 5.900777e-03
5204 chr13-113022287-113024304 F10       0.16108259 3.665475e-02
5225 chr14-23186887-23187657   HOMEZ     0.33680574 8.483196e-03
5267 chr14-39185741-39186661   TRAPPC6B  0.36383948 1.169085e-03
5278 chr14-49586417-49587081   RPS29    -0.25962276 3.907691e-02
5310 chr14-60625180-60625953   SIX4      0.30093247 1.809534e-03
5329 chr14-67738788-67739355   ZFYVE26   0.20922847 4.987006e-03
5541 chr5-131171039-131171605  HINT1    -0.04373167 1.475161e-02
5613 chr5-176388976-176389330  CLTB      0.09470763 8.660884e-03
5674 chr22-38218517-38219218   CSNK1E    0.24324441 1.102857e-02
5677 chr22-38261003-38262764   CSNK1E    0.19733548 2.335109e-02
5708 chr22-44668267-44668546   PRR5      0.23015375 4.105594e-02
5814 chr10-50550411-50550777   SGMS1     0.47685645 1.694983e-02
5920 chr10-99732101-99732219   ABCC2    -0.06097351 2.679541e-02
5937 chr10-103645252-103646270 SH3PXD2A -0.23896955 3.167467e-02
6154 chr15-65400947-65401783   IGDCC3   -0.09185287 3.163917e-02
6190 chr15-78108363-78108754   IDH3A     0.21828503 4.767480e-02
6217 chr15-89647075-89647595   KIF7      0.19661652 2.239187e-02